---
steps:
  - group: ":debian: Build & Package"
    steps:
      - label: "build package (amd64)"
        command: ".buildkite/build.sh"
        artifact_paths:
          - "build/*.deb"
        agents:
          queue: default
        plugins:
          - docker#v5.10.0:
              image: "${ECR}/jammybuild:master.latest"
              environment:
                - BUILDKITE_BUILD_NUMBER

      - label: "build package (arm64)"
        command: ".buildkite/build.sh"
        artifact_paths:
          - "build/*.deb"
        agents:
          queue: default_arm64
        plugins:
          - docker#v5.10.0:
              image: "${ECR}/jammybuild:master.latest"
              environment:
                - BUILDKITE_BUILD_NUMBER

  - block: "Release?"
    prompt: "Release to archive?"

  - label: ":debian: Publish deb"
    command:
      - >
        aptly-upload
        --aptly-url https://apt-repo.kx.gd
        --retries 3
        --repo kx-builds-jammy
        --series jammy
        build/*.deb
    retry:
      automatic: true
    plugins:
      artifacts#v1.9.3:
        download: "build/*.deb"
      docker#v5.10.0:
        image: "${ECR}/ci-tools"
        always-pull: true
        workdir: /src
        environment:
          - APTLY_UNAME
          - APTLY_PASSWD
